version: "3"
services:
  teste-postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - /home/andre/Documents/Data\ Structure/git-repo/BlueFishfy/API/docker-compose/postgreSQL/
    networks: 
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL} 
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD} 
    ports: 
      - "16543:80"
    depends_on: 
      - teste-postgres-compose
    networks: 
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge