version: '3.1'

services:
  postgres:
    image: postgres 
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=andre 
      - POSTGRES_PASSWORD=minhasenha
      - POSTGRES_DB= SONGS_T
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4 
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped 
    volumes:
      postgres-data: 