version: "3"
services:
  postgres-compose:
    image: postgres:12.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks: 
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL} 
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD} 
    ports: 
      - "15432:80"
    depends_on: 
      - postgres-compose
    networks: 
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  postgres-data:
    external: true