DROP TABLE IF EXISTS TB_HEROIS;

CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    PODER VARCHAR(45) NOT NULL
);

INSERT INTO TB_HEROIS(NOME, PODER)
VALUES
	('Flash','Speed'),
	('Aquaman','Speak with animals'),
	('Batman','Money')
; 
